### ISSUE TITLE
Support for Hetzner Cloud

### ISSUE THREAD

**Issue by Radiergummi** [promhippie/prometheus-hetzner-sd#131]
Do you plan to support [Hetzner Cloud](https://docs.hetzner.cloud) as well, or is that out of scope for the project? Would you need any help implementing support for that? We have relatively large project with dynamically registered cloud servers, so having proper service discovery for Prometheus would be great.

**Comment by tboerger** [comment]
There is already one at https://github.com/promhippie/prometheus-hcloud-sd ;)

**Comment by Radiergummi** [comment]
Oh, thank you very much! Seem to have missed that.
